### ISSUE TITLE
Unable to select album, KeyError: 'title'

### ISSUE THREAD

**Issue by chriswood1001** [Daanoz/ha-google-photos#4]
When choosing "Select Album" from the configuration menu I'm prompted with an "Error" dialogue, no additional information is provided. I'm other able to successfully authenticate ha-google-photos and see my favorite photos.

Release version v0.4.0
 
```
Logger: aiohttp.server
Source: custom_components/google_photos/config_flow.py:148
Integration: Google Photos (documentation, issues)
First occurred: 1:15:40 PM (2 occurrences)
Last logged: 1:15:48 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 267, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/google_photos/config_flow.py", line 176, in async_step_albumselect
    data_schema = await self._get_albumselect_schema()
  File "/config/custom_components/google_photos/config_flow.py", line 148, in _get_albumselect_schema
    album_selection[album["id"]] = album["title"]
KeyError: 'title'
```

**Comment by Daanoz** [comment]
Hmm strange, looks like some unexpected results are coming back from the Google Photos api. Add some extra sanity checks, could you see if 0.4.1 resolves your issue?

**Comment by Daanoz** [comment]
That would be correct, it's currently implemented as each album being a "device". It's a bit strange maybe, but it's the best way I could come up with matching the "albums" to the home assistant structure without creating a lot of entities if you have many albums.

For the "favorites" album, that gets created by default, but you can delete it from the device page and it will be removed from the integration.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/3742687/223227035-3c492465-8e2d-4d8b-81c1-a75f6911cde5.png">

**Comment by chriswood1001** [comment]
Ah, I overlooked that expecting each album to be set up as separate integrations (like ESPHome, Phone companion app or Glances). This certainly works — thanks for taking the time to create this!
